## Create Asset
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Itau",
    "symbol": "ITAU3",
    "price": 100,
}

###

@assetId = {{ createAsset.response.body._id }}

### Get All Assets
GET http://localhost:3000/assets

### Get Asset by ID
GET http://localhost:3000/assets/{{ assetId }}

### Delete Asset
DELETE http://localhost:3000/assets/{{ assetId }}

###############

### Create Wallet
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{ createWallet.response.body._id }}

### Get All Wallets
GET http://localhost:3000/wallets

### Get Wallet by ID
GET http://localhost:3000/wallets/{{ walletId }}

### Create Wallet Asset
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
    "assetId": "{{ assetId }}",
    "shares": 10
}

### Create Order
# @name createOrder
POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId": "{{ walletId }}",
    "assetId": "{{ assetId }}",
    "shares": 5,
    "type": "BUY"
}

###

@orderId = {{ createOrder.response.body._id }}

### Get All Orders
GET http://localhost:3000/orders


#### Get Order by ID
GET http://localhost:3000/orders/{{ orderId }}

### Get All With Filters
GET http://localhost:3000/orders?status=PENDING